name: flutter_wordle
description: A new game developed with Flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.13
  http: ^0.13.4
  html: ^0.15.0
  english_words: ^4.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Mulish
      fonts:
        - asset: fonts/mulish/Mulish-Bold.ttf
        - asset: fonts/mulish/Mulish-Light.ttf
        - asset: fonts/mulish/Mulish-Regular.ttf
    - family: League Gothic
      fonts:
        - asset: fonts/league_gothic/league-gothic-Regular.ttf